site_name: ASACA
repo_url: https://github.com/RhysonYang-2030/ASACA-Automatic-Speech-Analysis-for-Cognitive-Assessment
theme: material
plugins:
  - search
  - mkdocstrings
nav:
  - Home: index.md
  - Installation: installation.md
  - Tutorials: tutorials.md
  - API: reference.md
