name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]



jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        python-version: ["3.11"]
    steps:
      - uses: actions/checkout@v4
        if: always()                       
        with:
          name: coverage-${{ matrix.os }}  # coverage-ubuntu-latest / coverage-windows-latest
          path: coverage.xml
          
      - run: |
          echo "HEAD   = $(git rev-parse --abbrev-ref HEAD)"
          echo "PWD    = $PWD"
          ls -al

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
      
      - name: Install project + dev extras
        run: pip install -e ".[dev]"
        working-directory: ${{ github.workspace }}
      - run: ruff check .
      - run: mypy src/asaca
      - run: pytest --cov=src/asaca --cov-report=xml --color=yes
      - uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage.xml
