name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]



jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        python-version: ["3.11"]
    steps:
      - uses: actions/checkout@v4        # 不再带 path/name
    
      - name: Debug workspace
        run: |
          echo "HEAD   = $(git rev-parse --short HEAD)"
          echo "BRANCH = $(git rev-parse --abbrev-ref HEAD)"
          

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: pip

      - name: Install project + dev extras
        run: pip install -e ".[dev]"

      - run: ruff check .
      - run: mypy src/asaca
      - run: pytest --cov=src/asaca --cov-report=xml --color=yes
      - uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage.xml
