name: CI

on:
  push:
    branches: [ work ]
  pull_request:
    branches: [ work ]



jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        python-version: ["3.10", "3.11"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
      - run: pip install .[dev]
      - run: ruff check .
      - run: mypy src/asaca
      - run: pytest --cov=src/asaca --cov-report=xml
      - uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage.xml
